### ISSUE TITLE
need meta section

### ISSUE THREAD

**Issue by leipzig** [j-andrews7/awesome-bioinformatics-benchmarks#32]
need a section for papers about benchmarking theory

**Comment by j-andrews7** [comment]
You have any papers in mind for this? I'll try to add all the backlogged papers this week.

**Comment by leipzig** [comment]
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1738-8

**Comment by leipzig** [comment]
https://www.nature.com/articles/s41467-019-09406-4
