### ISSUE TITLE
Accuracy, Robustness and Scalability of Dimensionality Reduction Methods for Single Cell RNAseq Analysis

### ISSUE THREAD

**Issue by aedin** [j-andrews7/Awesome-Bioinformatics-Benchmarks#8]
Suggestion: 

Title: Accuracy, Robustness and Scalability of Dimensionality Reduction Methods for Single Cell RNAseq Analysis

Authors: Shiquan Sun, Jiaqiang Zhu, Ying Ma,  Xiang Zhou

Journal Info:  https://www.biorxiv.org/content/10.1101/641142v2

Description: Comparison of 18 different dimension reduction methods on 30 publicly available scRNAseq data sets  (28 real data and 2 simulated data).

Tools/methods compared:
18 different dimension reduction methods applied to single-cell RNA sequencing data

factor analysis (FA), principal component analysis (PCA), independent component analysis (ICA), Diffusion Map, nonnegative matrix factorization (NMF), Poisson NMF, zero-inflated factor analysis (ZIFA), zero-inflated negative binomial based wanted variation extraction (ZINB-WaVE), probabilistic count matrix factorization (pCMF), deep count autoencoder network (DCA), scScope, generalized linear model principal component analysis (GLMPCA), multidimensional scaling (MDS), locally linear embedding (LLE), local tangent space alignment (LTSA), Isomap, uniform manifold approximation and projection (UMAP), and t-distributed stochastic neighbor embedding (tSNE). 

Code is available from: https://github.com/xzhoulab/DRComparison

Recommendation(s):

Additional links (optional):

**Comment by j-andrews7** [comment]
Thanks, added.
